version: '3.8'

services:
  db:
    image: postgres:14
    container_name: orderbook-db
    environment:
      POSTGRES_DB: orderbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always

  
volumes:
  db_data:
